//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference3
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.ISensorService")]
    public interface ISensorService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISensorService/GetLatest", ReplyAction="http://tempuri.org/ISensorService/GetLatestResponse")]
        double GetLatest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISensorService/GetLatest", ReplyAction="http://tempuri.org/ISensorService/GetLatestResponse")]
        System.Threading.Tasks.Task<double> GetLatestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISensorService/SetLatest", ReplyAction="http://tempuri.org/ISensorService/SetLatestResponse")]
        void SetLatest(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISensorService/SetLatest", ReplyAction="http://tempuri.org/ISensorService/SetLatestResponse")]
        System.Threading.Tasks.Task SetLatestAsync(double value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ISensorServiceChannel : ServiceReference3.ISensorService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SensorServiceClient : System.ServiceModel.ClientBase<ServiceReference3.ISensorService>, ServiceReference3.ISensorService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SensorServiceClient() : 
                base(SensorServiceClient.GetDefaultBinding(), SensorServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISensorService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SensorServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SensorServiceClient.GetBindingForEndpoint(endpointConfiguration), SensorServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SensorServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SensorServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SensorServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SensorServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SensorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public double GetLatest()
        {
            return base.Channel.GetLatest();
        }
        
        public System.Threading.Tasks.Task<double> GetLatestAsync()
        {
            return base.Channel.GetLatestAsync();
        }
        
        public void SetLatest(double value)
        {
            base.Channel.SetLatest(value);
        }
        
        public System.Threading.Tasks.Task SetLatestAsync(double value)
        {
            return base.Channel.SetLatestAsync(value);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISensorService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISensorService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9003/SensorService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SensorServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISensorService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SensorServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISensorService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISensorService,
        }
    }
}
